Added section to read-me describing cross-shell tests, added cross-shell demo test; various fixes and cleanup.

diff --git a/urchin b/urchin
--- a/urchin
+++ b/urchin
@@ -21,7 +21,7 @@ recurse() {
   [ "$potential_test" = 'setup' ] && return
   [ "$potential_test" = 'teardown' ] && return
 
-  echo > "$stdout_file"
+  [ $indent_level -eq 0 ] && : > "$stdout_file"
 
   if [ -d "$potential_test" ]
     then
@@ -54,9 +54,9 @@ recurse() {
     [ -f teardown ] && [ -x teardown ] && ./teardown >> "$stdout_file"
 
     indent $indent_level
-    if [ "$exit_code" = '0' ]
+    if [ $exit_code -eq 0 ]
       then
-      # On success, print a '✓'
+      # On success, print a green '✓'
       printf '\033[32m✓ \033[0m'
       printf '%s\n' "${potential_test}"
       printf '%s\n' "${potential_test} passed" >> "$logfile"
@@ -65,10 +65,12 @@ recurse() {
       printf '\033[31m✗ \033[0m'
       printf '%s\n' "${potential_test}"
       printf '%s\n' "${potential_test} failed" >> "$logfile"
+      printf '\033[31m' # Print output captured from failed test in red.
       cat "$stdout_file"
+      printf '\033[0m'
     fi
-    rm "$stdout_file"
   fi
+  [ $indent_level -eq 0 ] && rm "$stdout_file"
 }
 
 USAGE="usage: $0 <test directory>"
@@ -77,12 +79,13 @@ urchin_help() {
   echo
   echo "$USAGE"
   echo
-  echo '-f      Force urchin to run on directories not named "test".'
+  echo '-f      Force urchin to run on directories whose name does not contain'
+  echo '        the word "test".'
   echo '-h      This help'
+  # echo
+  # echo '--xsd   Output xUnit XML schema for an integration server.'
   echo
-  echo '--xsd   Output xUnit XML schema for an integration server.'
-  echo
-  echo 'Go to http://www.urchin.sh for documentation on writing tests.'
+  echo 'Go to https://github.com/scraperwiki/urchin for documentation on writing tests.'
   echo
 }
 
@@ -99,36 +102,39 @@ plural () {
 }
 
 urchin_go() {
-  echo Running tests at $(date +%Y-%m-%dT%H:%M:%S)
+  echo Running tests at $(date +%Y-%m-%dT%H:%M:%S) | tee "$logfile"
   start=$(date +%s)
 
-  echo > "$logfile"
-  recurse "$1" 0
+  recurse "$1" 0  # test folder, indentation level
 
   finish=$(date +%s)
   elapsed=$(($finish - $start))
-  echo Done, took $elapsed $(plural second $elapsed)
+  echo "Done, took $elapsed $(plural second $elapsed)."
   set -- $(grep -e 'passed$' "$logfile"|wc -l) $(grep -e 'failed$' "$logfile"|wc -l)
   printf '%s\n' "$1 $(plural test "$1") passed."
+  [ $2 -gt 0 ] && printf '\033[31m' || printf '\033[32m' # If tests failed, print the message in red, otherwise in green.
   printf '%s\n' "$2 $(plural test "$2") failed."
+  printf '\033[m'
   return "$2"
 }
 
 urchin_molly_guard() {
-  echo
-  echo 'The directory on which you are running urchin is not'
-  echo 'called "test", so I am not running in case that'
-  echo 'was an accident. Use the -f flag if you really want'
-  echo 'to run urchin on that directory.'
-  echo
+  {
+    echo
+    echo 'The name of the directory on which you are running urchin'
+    echo 'does not contain the word "test", so I am not running,'
+    echo 'in case that was an accident. Use the -f flag if you really'
+    echo 'want to run urchin on that directory.'
+    echo
+  } >&2
   exit 1
 }
 
-FORCE=false
+force=false
 while [ $# -gt 0 ]
 do
     case "$1" in
-        -f) FORCE=true;;
+        -f) force=true;;
         -h|--help) urchin_help
           exit 0;;
 #       --xsd) action=testsuite;;
@@ -140,19 +146,20 @@ do
     shift
 done
 
+# Verify argument for main stuff
+if [ "$#" != '1' ] || [ ! -d "$1" ]
+  then
+  [ -d "$1" ] || echo "Not a directory: '$1'" >&2
+  echo "$USAGE" >&2
+  exit 1
+fi
+
 # Constants
 logfile=$(fullpath "$1")/.urchin.log
 stdout_file=$(fullpath "$1")/.urchin_stdout
 
-# Verify argument for main stuff
-if [ "$#" != '1' ] && [ ! -d "$1" ]
-  then
-  echo "$USAGE"
-  exit 1
-fi
-
 # Run or present the Molly guard.
-if basename "$(fullpath "$1")" | grep test > /dev/null || $FORCE
+if basename "$(fullpath "$1")" | grep -Fi 'test' > /dev/null || $force
   then
   urchin_go "$1"
 else
